### PR TITLE
Add some notes on setting up for development

### PR DESCRIPTION
**Pull request by davidread**

### CODE REVIEW

**Comment by davidread** [comment]
Ah cool, thanks for adding that.

**Comment by ivyleavedtoadflax** [comment]
These tests are failing - I think - because you aren't a member of the ukgovdatascience org. Just added you to the org, but I may need to make a new PR to get the tests to pass.

**Comment by davidread** [comment]
Ta for that. I've poked Travis to rebuild, and if it still fails I've create a new PR on the main repo.

**Comment by ivyleavedtoadflax** [comment]
Replicated in #102 to allow tests to pass.

**Pull request closed without merging**
